#!/bin/sh

# Check if rule already exists
iptablesrules=$(iptables -L PREROUTING -t nat | grep "jenkins" | wc -l)

# If not, add it
if [ $iptablesrules -eq 0 ]; then
  iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080 -m comment --comment "jenkins"
fi

exit 0
