#!/bin/bash

ROOT=`dirname $0`/..

# Make sure that all of the Secrets and prerequisites are in place.

HAS_RAXREGION=0
HAS_ANSIBLE=0
HAS_PYRAX=0
HAS_DRGPEM=0
HAS_PUBLISHERKEY=0
HAS_IPLIST=0

[ -f ${HOME}/.ssh/drg.pem ] && HAS_DRGPEM=1
[ -f ${ROOT}/deploy/roles/jenkins_masters/files/var/lib/jenkins/publisher.id_rsa ] && HAS_PUBLISHERKEY=1
[ -f ${ROOT}/deploy/ip_access.yml ] && HAS_IPLIST=1

if [ ! $HAS_DRGPEM ] || [ ! $HAS_PUBLISHERKEY ] || [ ! $HAS_IPLIST ]; then
  echo "Uh oh! You're missing some things you'll need to get started."
  echo

  if [ ! $HAS_DRGPEM ]; then
    echo "* The drg.pem private key is missing."
    echo "  Put it at ${HOME}/.ssh and chmod it 600."
  fi

  if [ ! $HAS_PUBLISHERKEY ]; then
    echo "* The publisher.id_rsa private key is missing."
    echo "  Download it and put it in deploy/roles/jenkins_masters/files/var/lib/jenkins/publisher.id_rsa."
  fi

  if [ ! $HAS_IPLIST ]; then
    echo "* The IP whitelist is missing."
    echo "  Put it at deploy/ip_access.yml. You can also set it to your own IP for testing"
    echo "  and development. Follow the format found in deploy/ip_access.yml.example."
  fi

  echo
  echo "Give it another shot once you've tracked those down."

  exit 1
fi

# Kick it. Pass any additional arguments to Ansible.

cd ${ROOT}/deploy
ansible-playbook -i inventory/site site.yml
