#!/usr/bin/env python
#
# Output a summary of recent alarm notifications.

import pyrax
import os
import json

pyrax.set_setting("identity_type", "rackspace")
pyrax.set_setting("region", os.environ['RAX_REGION'].upper())
pyrax.set_credential_file(os.path.expanduser("~/.rackspace_cloud_credentials"))

cm = pyrax.cloud_monitoring

# Find the checks that we care about.

for e in cm.list_entities():
    for a in e.list_alarms():
        uri = '/entities/%s/alarms/%s/notification_history' % (e.id, a.id)
        resp, resp.body = cm.method_get(uri)

        for cid in resp.body['check_ids']:
            c = cm.get_check(e, cid)
            print('%s :: %s :: %s' % (e.label, a.label, c.label))
            print

            uri = '/entities/%s/alarms/%s/notification_history/%s?reverse=true' % (e.id, a.id, cid)
            resp, resp.body = cm.method_get(uri)

            for each in resp.body['values']:
                print(json.dumps(each, sort_keys=True, indent=2, separators=(',', ': ')))
                print
