#!/usr/bin/env python
#
# List the current state of monitoring.

import pyrax
import os

pyrax.set_setting("identity_type", "rackspace")
pyrax.set_setting("region", os.environ['RAX_REGION'])
pyrax.set_credential_file(os.path.expanduser("~/.rackspace_cloud_credentials"))

cm = pyrax.cloud_monitoring

def attempt_nuke(monitor_element):
  try:
    monitor_element.delete()
    print("DELETED {}".format(monitor_element))
  except Exception as e:
    print("Can't delete {}".format(monitor_element))
    print(e)

print ">> ENTITIES ::"
for e in cm.list_entities():
  attempt_nuke(e)

print ">> CHECKS ::"
for e in cm.list_entities():
    checks = e.list_checks()
    if len(checks) > 0:
        print "- %s" % e.label
    for c in e.list_checks():
        attempt_nuke(c) 

print ">> NOTIFICATIONS ::"
for n in cm.list_notifications():
    attempt_nuke(n)

print ">> NOTIFICATION PLANS ::"
for np in cm.list_notification_plans():
    attempt_nuke(np)

print ">> ALARMS ::"
for e in cm.list_entities():
    alarms = e.list_alarms()
    if len(alarms) > 0:
        print "- %s" % e.label
    
    for a in e.list_alarms():
        attempt_nuke(a)
